resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
  - repository: adf
    type: github
    name: JFolberth/adf_yaml_ci_cd
    endpoint: JFolberth
    ref: refs/heads/main
trigger:
- main

pool:
  name: 'container-apps'

stages:
    - template: adf_pipelines_template.yml
