resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: refs/heads/feature/adf_and_pipelines
  - repository: adf
    type: github
    name: JFolberth/adf_yaml_ci_cd
    endpoint: JFolberth
    ref: refs/heads/main
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
    - checkout: adf
    - template: adf_pipelines_template.yml
