parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'
      regionAbrvs: ['eus']
      locations: ['eastus']
    - environmentName: 'tst'
      regionAbrvs: ['eus']
      locations: ['eastus']
- name: serviceName
  type: string
  default: 'adfdemo'
- name: linkedTemplates
  type: boolean
  default: true

  
stages:
- template: stages/adf_build_stage.yml@templates
  parameters:
    serviceName: ${{ parameters.serviceName }}
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
  - template: stages/adf_deploy_stage.yml@templates
    parameters:
      environmentObjects: ${{ parameters.environmentObjects }}
      serviceName: ${{ parameters.serviceName }}
      linkedTemplates: ${{ parameters.linkedTemplates }}
