resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: refs/heads/feature/adf_yaml_templates
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
    - template: adf_pipelines_template.yml
